server:
  port: 8080

spring:
  datasource:
    username: root
    password: 114514
    url: jdbc:mysql://127.0.0.1:3306/novelnook?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

