server:
  port: 8080

spring:
  datasource:
    username: root
    password: sjh123456
    url: jdbc:mysql://localhost:3306/novelnook?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
